### PR TITLE
Remove excess logging

### PR DESCRIPTION
**Pull request by dgenr8**
Suppress logging in CheckProofOfWork when using the reference cpuminer.

### CODE REVIEW

**Comment by dgenr8** [comment]
@cryptozeny

**Comment by cryptozeny** [comment]
i ran your build f344f29, but it seems freezing at startup. testnet. i cannot reproduce, but it randomly appears.

image

**Comment by cryptozeny** [comment]
image

**Comment by cryptozeny** [comment]
image

**Comment by cryptozeny** [comment]
`setgenerate true 1` OK as before

**Comment by dgenr8** [comment]
@cryptozeny Thank, I pushed an update to this PR to fix a misplaced parenthesis.  Please try again.

Be aware that 'generate 1' is unlikely to succeed on testnet because it defaults to 1,000,000 hash tries.  At minimum, testnet (=mainnet) difficulty you need about 7,000,000 * 600 = about 4,200,000,000 tries.  You can enter # of tries in the next parameter. Anyway it should not return an error anymore.

**Comment by cryptozeny** [comment]
3d2b1e4 no error on `generate 1`

**Comment by cryptozeny** [comment]
> Be aware that 'generate 1' is unlikely to succeed on testnet because it defaults to 1,000,000 hash tries. At minimum testnet (=mainnet) difficulty you need about 7,000,000 * 600 = about 4,200,000,000 tries. You can enter # of tries in the next parameter.

but out of range

image

**Comment by dgenr8** [comment]
Rebased to remove duplicate of the 200GB fix.

**Comment by dgenr8** [comment]
Thanks @cryptozeny!

**Pull request merged**
